# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='account_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
