# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_bank', '0002_accounts_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='account_date',
        ),
    ]
