# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_bank', '0003_remove_accounts_account_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='balance',
            field=models.IntegerField(default=300),
        ),
    ]
