# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('company_name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=10)),
                ('conf_pass', models.CharField(max_length=10)),
                ('license_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('city', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=25)),
                ('published_date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
