# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_bis1', '0002_auto_20160409_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='published_date',
        ),
    ]
