# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_bis1', '0003_remove_signup_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
        migrations.AddField(
            model_name='signup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
