# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_bis1', '0005_iteminfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminfo',
            name='license_id',
            field=models.IntegerField(max_length=100),
        ),
    ]
